// <auto-generated />
using System;
using System.Collections.Generic;
using MangaTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangaTracker.Api.Migrations
{
    [DbContext(typeof(MangaTrackerDbContext))]
    [Migration("20260307011131_AddRankingHome")]
    partial class AddRankingHome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangaTracker.Models.AdminLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("MangaTracker.Models.Editora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Editoras");
                });

            modelBuilder.Entity("MangaTracker.Models.Leitura", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MangaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CapituloAtual")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaLeituraEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "MangaId");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("MangaTracker.Models.Manga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnoLancamentoBrasil")
                        .HasColumnType("integer");

                    b.Property<int?>("AnoLancamentoOriginal")
                        .HasColumnType("integer");

                    b.Property<string>("Autor")
                        .HasColumnType("text");

                    b.Property<string>("CapaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Demografia")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid?>("EditoraId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Generos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("LancadoNoBrasil")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCapitulos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EditoraId");

                    b.ToTable("Catalogo");
                });

            modelBuilder.Entity("MangaTracker.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MangaTracker.Models.Manga", b =>
                {
                    b.HasOne("MangaTracker.Models.Editora", "EditoraNav")
                        .WithMany()
                        .HasForeignKey("EditoraId");

                    b.Navigation("EditoraNav");
                });
#pragma warning restore 612, 618
        }
    }
}
